import { afterEach, describe, expect, it, vi } from 'vitest'
import { createUserSession } from './userSession'

const profile = { id: 'family-profile', name: 'Eoin', avatar_url: '' }
const settle = async () => { for (let i = 0; i < 12; i++) await Promise.resolve() }
function setup() {
  const fetchProfile = vi.fn().mockResolvedValue(new Response(JSON.stringify({ data: profile })))
  const update = vi.fn()
  const unauthorized = vi.fn()
  const session = createUserSession({ fetchProfile, update, unauthorized })
  return { session, fetchProfile, update, unauthorized }
}
afterEach(() => vi.useRealTimers())

describe('session profile loading', () => {
  it('loads once and ignores repeated same-user sign-in notifications', async () => {
    const { session, fetchProfile, update } = setup()
    session.handle('INITIAL_SESSION', 'auth-user')
    session.handle('SIGNED_IN', 'auth-user')
    await settle()
    expect(update).toHaveBeenLastCalledWith({ user: profile, isLoading: false })
    update.mockClear()
    session.handle('SIGNED_IN', 'auth-user')
    expect(fetchProfile).toHaveBeenCalledTimes(1)
    expect(update).not.toHaveBeenCalled()
    session.dispose()
  })
  it('keeps the loaded page visible during token refresh and transient failures', async () => {
    const { session, fetchProfile, update } = setup()
    session.handle('INITIAL_SESSION', 'a')
    await settle()
    update.mockClear()
    fetchProfile.mockRejectedValue(new Error('offline'))
    session.handle('TOKEN_REFRESHED', 'a')
    await settle()
    expect(update).toHaveBeenCalledOnce()
    expect(update).toHaveBeenLastCalledWith({ user: profile, isLoading: false })
    session.dispose()
  })
  it.each(['SIGNED_OUT', 'account-change', 'dispose'])('ignores late responses after %s', async action => {
    const { session, fetchProfile, update } = setup()
    let resolve!: (value: Response) => void
    fetchProfile.mockImplementationOnce(() => new Promise<Response>(r => { resolve = r }))
    session.handle('INITIAL_SESSION', 'a')
    if (action === 'SIGNED_OUT') session.handle('SIGNED_OUT', null)
    else if (action === 'account-change') session.handle('SIGNED_IN', 'b')
    else session.dispose()
    await settle()
    update.mockClear()
    resolve(new Response(JSON.stringify({ data: { ...profile, name: 'Stale' } })))
    await settle()
    expect(update).not.toHaveBeenCalled()
    session.dispose()
  })
  it('clears the old account immediately on an account change', async () => {
    const { session, update } = setup()
    session.handle('INITIAL_SESSION', 'a')
    await settle()
    session.handle('SIGNED_IN', 'b')
    expect(update).toHaveBeenLastCalledWith({ user: null, isLoading: true })
    session.dispose()
  })
  it.each([401, 403])('clears and redirects on profile status %s', async status => {
    const { session, fetchProfile, update, unauthorized } = setup()
    fetchProfile.mockResolvedValue(new Response(null, { status }))
    session.handle('INITIAL_SESSION', 'a')
    await settle()
    expect(update).toHaveBeenLastCalledWith({ user: null, isLoading: false })
    expect(unauthorized).toHaveBeenCalledOnce()
    session.dispose()
  })
  it('updates the profile in the background and clears it if access is revoked', async () => {
    const { session, fetchProfile, update, unauthorized } = setup()
    session.handle('INITIAL_SESSION', 'a')
    await settle()
    update.mockClear()
    const updatedProfile = { ...profile, name: 'Updated' }
    fetchProfile.mockResolvedValueOnce(new Response(JSON.stringify({ data: updatedProfile })))
    session.handle('USER_UPDATED', 'a')
    expect(update).not.toHaveBeenCalled()
    await settle()
    expect(update).toHaveBeenLastCalledWith({ user: updatedProfile, isLoading: false })
    fetchProfile.mockResolvedValueOnce(new Response(null, { status: 403 }))
    session.handle('TOKEN_REFRESHED', 'a')
    await settle()
    expect(update).toHaveBeenLastCalledWith({ user: null, isLoading: false })
    expect(unauthorized).toHaveBeenCalledOnce()
    session.dispose()
  })
  it.each(['TOKEN_REFRESHED', 'USER_UPDATED'] as const)('restarts an older pending request on %s', async event => {
    const { session, fetchProfile, update } = setup()
    let resolve!: (response: Response) => void
    fetchProfile.mockImplementationOnce(() => new Promise<Response>(r => { resolve = r }))
    session.handle('INITIAL_SESSION', 'a')
    const oldSignal = fetchProfile.mock.calls[0][0] as AbortSignal
    session.handle(event, 'a')
    expect(fetchProfile).toHaveBeenCalledTimes(2)
    expect(oldSignal.aborted).toBe(true)
    await settle()
    expect(update).toHaveBeenLastCalledWith({ user: profile, isLoading: false })
    update.mockClear()
    resolve(new Response(JSON.stringify({ data: { ...profile, name: 'Stale' } })))
    await settle()
    expect(update).not.toHaveBeenCalled()
    session.dispose()
  })
  it('aborts the request on sign-out', () => {
    const { session, fetchProfile } = setup()
    fetchProfile.mockImplementation(() => new Promise(() => {}))
    session.handle('INITIAL_SESSION', 'a')
    const signal = fetchProfile.mock.calls[0][0] as AbortSignal
    session.handle('SIGNED_OUT', null)
    expect(signal.aborted).toBe(true)
    session.dispose()
  })
  it('settles signed-out initialization without fetching', () => {
    const { session, fetchProfile, update } = setup()
    session.handle('INITIAL_SESSION', null)
    expect(update).toHaveBeenLastCalledWith({ user: null, isLoading: false })
    expect(fetchProfile).not.toHaveBeenCalled()
    session.dispose()
  })
  it('ends initial loading after a stalled profile request and permits retry', async () => {
    vi.useFakeTimers()
    const { session, fetchProfile, update } = setup()
    fetchProfile.mockImplementationOnce(() => new Promise(() => {}))
    session.handle('INITIAL_SESSION', 'a')
    await vi.advanceTimersByTimeAsync(10_000)
    expect(update).toHaveBeenLastCalledWith({ user: null, isLoading: false })
    session.handle('SIGNED_IN', 'a')
    await settle()
    expect(fetchProfile).toHaveBeenCalledTimes(2)
    session.dispose()
  })
})
